---
apiVersion: v1
kind: Service
metadata:
  name: home-inspire
  labels:
    name: home-inspire
    app: homeinspire
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30003
  selector:
    name: home-inspire
    app: homeinspire